Backend produto
DLL-S/ueg-construcao-software pull request #29
Opened 2021-01-25 11:42 UTC by danyelliasmanso

2021-01-25 16:07 UTC, lucasdemoraesc requested changes

2021-01-25 16:07 UTC, lucasdemoraesc commented on Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/exception/ResourceNotFoundException.java
> +package com.dlls.pecacerta.api.exception;
Alterar nome do package
De:
**com.dlls.pecacerta.api.exception**
Para:
**com.dlls.pecacerta.api.exceptions**

2021-01-25 16:07 UTC, lucasdemoraesc commented on Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/model/Endereco.java
> -package com.dlls.pecacerta.api.model;
Exclusão do arquivo irá gerar conflitos

2021-01-25 16:07 UTC, lucasdemoraesc commented on Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/model/Funcionario.java
> -package com.dlls.pecacerta.api.model;
Exclusão do arquivo irá gerar conflitos

2021-01-25 16:29 UTC, danyelliasmanso commented on Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/PecacertaApiApplication.java
> +
@lucasdemoraesc, deixar o arquivo desta forma?
![image](https://user-images.githubusercontent.com/56615063/105734397-5b8d4600-5f11-11eb-986d-c12c36e841f3.png)

2021-01-25 18:14 UTC, lucasdemoraesc commented
Hein, altera o nome do package de cobtrollers tbm (https://github.com/DLL-S/ueg-construcao-software/discussions/26)

Não reparei quando revisei...

2021-01-25 18:17 UTC, lucasdemoraesc commented on Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/PecacertaApiApplication.java
> +
Isso

2021-01-25 18:18 UTC, danyelliasmanso commented on Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/PecacertaApiApplication.java
> +
Alteração feita e comitada para o o branch Backend produto.

2021-01-25 18:26 UTC, lucasdemoraesc commented on Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/repositories/ProdutoRepository.java
> +
Como produtos também podem ser pesquisados por nome ou parte do nome, faltou a declaração do método findByNome

2021-01-25 18:26 UTC, lucasdemoraesc commented on Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/exceptions/ResourceNotFoundException.java
> +public class ResourceNotFoundException extends Exception {
Cara, antes de dar Merge, @leonardopereira10 vamos decidir se vamos seguir o padrão de exceções que eu e você usamos, ou se deixamos isso aberto (cada um implementa do seu jeito)

2021-01-25 19:00 UTC, danyelliasmanso commented on Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/repositories/ProdutoRepository.java
> +
Ainda não implementei esse método, posteriormente será implementado.

2021-01-27 02:53 UTC, lucasdemoraesc approved these changes

2021-01-27 03:04 UTC, merged